import { BookProvider } from "context/BookContext";
import type { Metadata } from "next";
import { SessionProvider } from "next-auth/react";
import { Inter } from "next/font/google";
import { ReactNode } from "react";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type Props = {
  children: ReactNode;
  session: any;
};

export default function RootLayout({ children, session }: Props) {
  return (
    <BookProvider>
      <SessionProvider session={session}>
        <html lang="en">
          <body className={inter.className}>{children}</body>
        </html>
      </SessionProvider>
    </BookProvider>
  );
}
